import imagePath from './imagePath';
export default [
  {
    id: 1,
    categoryName: 'Burger',
    categoryIcon: imagePath.burgerIcon,
    alternateHotels: [
      {
        hotelName: 'Shiva Sagar',
        hotelLocation: 'Konchadi',
        hotelArea: 'Mangalore',
        hotelState: 'Karnataka',
        hotelCountry: 'India',
        hotelRating: 4.5,
        hotelImage: imagePath.shivSagar,
      },
      {
        hotelName: 'Vrindavan',
        hotelLocation: 'Circuit House',
        hotelArea: 'Mangalore',
        hotelState: 'Karnataka',
        hotelCountry: 'India',
        hotelRating: 4.6,
        hotelImage: imagePath.vrindavan,
      },
      {
        hotelName: 'Vardhaman',
        hotelLocation: 'Yeyyadi',
        hotelArea: 'Mangalore',
        hotelState: 'Karnataka',
        hotelCountry: 'India',
        hotelRating: 4.4,
        hotelImage: imagePath.vardhaman,
      },
    ],
    menu: [
      {
        itemId: 1,
        itemName: 'Sub Sandwich',
        type: 'Fastfood',
        rating: 4.5,
        cost: '15.50',
        image: imagePath.subSandwichImage,
        ingredients: [
          {name: 'potato'},
          {name: 'cheese'},
          {name: 'lettuce'},
          {name: 'buns'},
          {name: 'chilli'},
          {name: 'salt'},
          {name: 'pepper'},
          {name: 'oil'},
        ],
        ingredientImages: [
          {icon: imagePath.potatoIcon1},
          {icon: imagePath.cheeseIcon},
          {icon: imagePath.lettuceIcon},
          {icon: imagePath.bunsIcon},
          {icon: imagePath.chilliIcon},
          {icon: imagePath.saltIcon},
          {icon: imagePath.pepperIcon},
          {icon: imagePath.oilIcon},
        ],
        timeDuration: '5-10 mins',
        description:
          'Cheeses like Cheddar, Gruyere, Parmesan, and Its Pecorino work well with all kinds of burgers',
      },
      {
        itemId: 2,
        itemName: 'Cheese Burger',
        type: 'Fastfood',
        rating: 4.5,
        cost: '13.00',
        image: imagePath.burgerImage,
        ingredients: [
          {name: 'potato'},
          {name: 'cheese'},
          {name: 'lettuce'},
          {name: 'tomato'},
          {name: 'buns'},
          {name: 'chilli'},
          {name: 'salt'},
          {name: 'pepper'},
          {name: 'oil'},
        ],
        ingredientImages: [
          {icon: imagePath.potatoIcon1},
          {icon: imagePath.cheeseIcon},
          {icon: imagePath.lettuceIcon},
          {icon: imagePath.tomatoIcon},
          {icon: imagePath.bunsIcon},
          {icon: imagePath.chilliIcon},
          {icon: imagePath.saltIcon},
          {icon: imagePath.pepperIcon},
          {icon: imagePath.oilIcon},
        ],
        timeDuration: '15-30 mins',
        description:
          'Cheeses like Cheddar, Gruyere, Parmesan, and Its Pecorino work well with all kinds of burgers',
      },
      {
        itemId: 3,
        itemName: 'Potato Fries',
        type: 'Fastfood',
        rating: 4.5,
        cost: '12.00',
        image: imagePath.potatoFries,
        ingredients: [
          {name: 'potato'},
          {name: 'chilli'},
          {name: 'salt'},
          {name: 'oil'},
          {name: 'water'},
        ],
        ingredientImages: [
          {icon: imagePath.potatoIcon1},
          {icon: imagePath.chilliIcon},
          {icon: imagePath.saltIcon},
          {icon: imagePath.oilIcon},
          {icon: imagePath.waterIcon},
        ],
        timeDuration: '15-20 mins',
        description:
          'Cheeses like Cheddar, Gruyere, Parmesan, and Its Pecorino work well with all kinds of burgers',
      },
      {
        itemId: 4,
        itemName: 'French Fries',
        type: 'Fastfood',
        rating: 4.5,
        cost: '12.50',
        image: imagePath.frenchFries,
        ingredients: [
          {name: 'potato'},
          {name: 'chilli'},
          {name: 'salt'},
          {name: 'pepper'},
          {name: 'oil'},
          {name: 'water'},
        ],
        ingredientImages: [
          {icon: imagePath.potatoIcon1},
          {icon: imagePath.chilliIcon},
          {icon: imagePath.saltIcon},
          {icon: imagePath.pepperIcon},
          {icon: imagePath.oilIcon},
          {icon: imagePath.waterIcon},
        ],
        timeDuration: '25-30 mins',
        description:
          'Cheeses like Cheddar, Gruyere, Parmesan, and Its Pecorino work well with all kinds of burgers',
      },
    ],
  },
  {
    id: 2,
    categoryName: 'Pizza',
    categoryIcon: imagePath.pizzaIcon,
  },
  {
    id: 3,
    categoryName: 'Dessert',
    categoryIcon: imagePath.dessertIcon,
  },
  {
    id: 4,
    categoryName: 'Fries',
    categoryIcon: imagePath.friesIcon,
  },
  {
    id: 5,
    categoryName: 'Drinks',
    categoryIcon: imagePath.drinkscon,
  },
  {
    id: 6,
    categoryName: 'Pasta',
    categoryIcon: imagePath.pastaIcon,
  },

  {
    id: 7,
    categoryName: 'Popular',
    categoryIcon: imagePath.fastFoodIcon2,
  },
];
