import imagePath from './imagePath';
export default [
  {
    id: 1,
    categoryName: 'Burger',
    alternateHotels: [
      {
        hotelName: 'Shiva Sagar',
        hotelLocation: 'Konchadi',
        hotelArea: 'Mangalore',
        hotelState: 'Karnataka',
        hotelCountry: 'India',
        hotelRating: 4.5,
        hotelImage: imagePath.shivSagar,
      },
      {
        hotelName: 'Vrindavan',
        hotelLocation: 'Circuit House',
        hotelArea: 'Mangalore',
        hotelState: 'Karnataka',
        hotelCountry: 'India',
        hotelRating: 4.6,
        hotelImage: imagePath.vrindavan,
      },
      {
        hotelName: 'Vardhaman',
        hotelLocation: 'Yeyyadi',
        hotelArea: 'Mangalore',
        hotelState: 'Karnataka',
        hotelCountry: 'India',
        hotelRating: 4.4,
        hotelImage: imagePath.vardhaman,
      },
    ],
    menu: [
      {
        itemId: 1,
        itemName: 'Sub Sandwich',
        type: 'Fastfood',
        rating: 4.5,
        cost: '15.50',
        image: imagePath.subSandwichImage,
        ingredients: [
          {name: 'potato'},
          {name: 'cheese'},
          {name: 'lettuce'},
          {name: 'buns'},
        ],
        ingredientImages: [
          {icon: imagePath.potatoIcon1},
          {icon: imagePath.cheeseIcon},
          {icon: imagePath.lettuceIcon},
          {icon: imagePath.bunsIcon},
        ],
      },
      {
        itemId: 2,
        itemName: 'Cheese Burger',
        type: 'Fastfood',
        rating: 4.5,
        cost: '13.00',
        image: imagePath.burgerImage,
        ingredients: '',
        ingredientImages: [],
      },
      {
        itemId: 3,
        itemName: 'Potato Fries',
        type: 'Fastfood',
        rating: 4.5,
        cost: '12.00',
        image: imagePath.potatoFries,
        ingredients: '',
        ingredientImages: [],
      },
      {
        itemId: 4,
        itemName: 'French Fries',
        type: 'Fastfood',
        rating: 4.5,
        cost: '12.50',
        image: imagePath.frenchFries,
        ingredients: '',
        ingredientImages: [],
      },
    ],
  },
  {
    id: 2,
    categoryName: 'Pizza',
  },
  {
    id: 3,
    categoryName: 'Dessert',
  },
  {
    id: 4,
    categoryName: 'Fries',
  },
  {
    id: 5,
    categoryName: 'Drinks',
  },
];
